In [2]:
import numpy as np

In [3]:
# 1D array
# to create an array with list
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [6]:
# this is a string array, which is not well optimized and we should avoid mixing numerics with string.
np.array([1, 2, 3, 4, 5, 'shayan'])

array(['1', '2', '3', '4', '5', 'shayan'], dtype='<U21')

In [9]:
# 2D array
# list in list array
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
# 3D array
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# what we can't do is creating array with different len in dimension

# np.array([[1,2,3],[4,5,6,7]])
#  error : The requested array has an inhomogeneous shape after 1 dimensions.

In [14]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [15]:
type(arr2)

numpy.ndarray

In [17]:
np.shape(arr2)   # (2,3)   2-rows 3-columns

(2, 3)

In [25]:
import time
l1 = list(range(5000))

# python list - loops
start_list = time.time()
l2 = [x**2 for x in l1]
end_list = time.time()
print('Time taken by list ', (end_list-start_list))
# print(l2)

# numpy array - vectorization
l3 = np.array(l1)
start_np = time.time()
l3 = l3 ** 2
end_np = time.time()
print('Time taken by array : ',  end_np - start_np)
# print(l3)

Time taken by list  0.0011553764343261719
Time taken by array :  0.0002961158752441406
