In [1]:
import numpy as np

In [2]:
# when you what to install any package in jupyter we start with ! and write like this.
!pip install numpy

# to install the same on your local python : pip install python

In [3]:
arr1 = np.array([1,2,3,4,5]) # 1D array
arr2 = np.array([[1,2,3],[4,5,6]]) #2D array

In [4]:
type(arr1)

numpy.ndarray

In [5]:
type(arr2)

numpy.ndarray

In [6]:
np.shape(arr1)

(5,)

In [7]:
np.shape(arr2)

(2, 3)

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [12]:
np.full((3,3), 17)

array([[17, 17, 17],
       [17, 17, 17],
       [17, 17, 17]])

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
# arange(start, end, step) : start, start + step, start + step +step, start + step + step + step....
np.arange(0,100,9) #array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

array([ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81, 90, 99])

In [17]:
# linspace(start,end,count) : this will evenly space the values from start to end in the number of count given
np.linspace(0,10,5) # array([ 0. ,  2.5,  5. ,  7.5, 10. ])

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [24]:
# np.shape(my_arr)
my_arr.shape

(4, 3)

In [25]:
# np.size(my_arr)
my_arr.size

12

In [26]:
# np.ndim(my_arr)
my_arr.ndim

2

In [27]:
# np.dtype(my_arr)
my_arr.dtype

dtype('int64')

In [28]:
# we can explicitly mention the data type.
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], dtype = 'float32')

In [29]:
my_arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]], dtype=float32)

In [30]:
# we can also modify the data type by using : astype
n = my_arr.astype('float64')

In [31]:
n

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [11., 12., 13.]])

In [32]:
type(n)

numpy.ndarray

In [34]:
n.dtype

dtype('float64')

In [35]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [36]:
my_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [37]:
my_arr.shape

(4, 3)

In [40]:
# we can also reshape the array
# we can reshape into any count unless the rows*columns values are same : 4*3, 3*4, 6*2, 2*6, 12*1
reshaped = my_arr.reshape((3,4))

In [41]:
reshaped

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 11, 12, 13]])

In [43]:
reshaped1 = my_arr.reshape((2,6))

In [44]:
reshaped1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 11, 12, 13]])

In [45]:
reshaped3 = my_arr.reshape((12,1))

In [46]:
reshaped3

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [11],
       [12],
       [13]])

In [47]:
reshaped4 = my_arr.reshape((2,5))
# cannot reshape array of size 12 into shape (2,5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [48]:
my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [49]:
my_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [50]:
my_arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])