In [1]:
import numpy as np

my_arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [2]:
my_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = my_arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
# indexing
print(flat[0])
print(flat[3])
print(flat[6])
print(flat[-1])
print(flat[-2])
print('This is the length of the array : ',len(flat))

1
4
7
13
12
This is the length of the array :  12


In [6]:
# slicing
print(flat[:])
print(flat[:4])
print(flat[6:])
print(flat[::-1])
print(flat[0:3])
print(flat[0:8:2])

[ 1  2  3  4  5  6  7  8  9 11 12 13]
[1 2 3 4]
[ 7  8  9 11 12 13]
[13 12 11  9  8  7  6  5  4  3  2  1]
[1 2 3]
[1 3 5 7]


## slicing returns a view not a copy. Changes in copy takes affect in original array
- flat_arr is original array.
- b is a variable where i have sliced flat_arr
- now when i modify any element of b
- same element of flat_arr also gets affected

Theory
- This happens because numpy does not give you copy while slicing.
- Instead, it gives you the original view of the memory for the slice.
- As, they share the same memory any modification in sliced item will change in the original array and vice-versa.
- for eficient memory

In [7]:
flat_arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [8]:
flat_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [9]:
b = flat_arr[3:7] # this should give me element indexed at 3, 4, 5, 6

In [10]:
b

array([4, 5, 6, 7])

In [11]:
b[0] = 4444   # this will modify b[0] but also flat_arr[3]

In [12]:
b

array([4444,    5,    6,    7])

In [13]:
flat_arr

array([   1,    2,    3, 4444,    5,    6,    7,    8,    9,   11,   12,
         13])

In [14]:
flat_arr[6] = 17171717

In [15]:
b

array([    4444,        5,        6, 17171717])

In [17]:
# But we can take a .copy() from the array if we want a copy which should not change the original array
c = flat_arr[0:4].copy()

In [18]:
c

array([   1,    2,    3, 4444])

In [19]:
c[3] = 4

In [20]:
c

array([1, 2, 3, 4])

In [21]:
flat_arr

array([       1,        2,        3,     4444,        5,        6,
       17171717,        8,        9,       11,       12,       13])

In [22]:
# Fancy indexing : you cna give multiple index in the form of list

arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [23]:
# Boolean masking : the condition you give in [], will filter the items of the array

arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]


In [24]:
# excercise 1 : create 3by3 array with random number, get the shape

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [25]:
# ex2 : convert float array to int
arr = np.array([1.1, 2.2, 3.3], dtype='int64')
print(arr)

[1 2 3]


In [29]:
# ex3 : fancy indexing to extract even numbers
arr = np.array([1,2,3,4,5,6])
even_index = [1,3,5]
print(arr[idx])

[1 3 5]


In [30]:
# ex4: reshape 1D array of 9 items to 3by3
arr = np.array([1,2,3,4,5,6,7,8,9])

arr_3d = arr.reshape([3,3])
print(arr_3d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [33]:
# ex5 : boolean masking filter the numbers greater than 50

arr = np.array([x*10 for x in range(11)])
print(arr[arr > 50])

[ 60  70  80  90 100]
