In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr # 2D array : 2axes (axis 0 : rows, axis 1: columns)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr.ndim

2

In [5]:
arr[0] # operation goes down the rows

array([1, 2, 3])

In [6]:
arr[1]

array([4, 5, 6])

In [7]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.sum(arr, axis=0) # adds item of rows from top to down

array([12, 15, 18])

In [9]:
np.sum(arr, axis=1) # adds item of column from left to right

array([ 6, 15, 24])

In [10]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# indexing
arr[0][1] # 0 row, column 1 index

np.int64(2)

In [12]:
arr[0 , 2] # in 0 row, item at index 2

np.int64(3)

In [13]:
arr[0:2] # slicing 0 row, 1 row, slicing here is [0 : n-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr[0:2,1:3] # row 0 and row 1, col 1 and col 2

array([[2, 3],
       [5, 6]])

In [15]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [16]:
arr3d #3d has 3 [depth or layer : row: column]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [17]:
arr3d.ndim

3

In [18]:
arr3d[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [19]:
arr3d[:,0,0]

array([1, 7])

In [20]:
arr3d[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [21]:
arr3d[0,0,1:3]

array([2, 3])

In [22]:
# index assignment
# we can slice a view and update the value and the value in original array will also get updated
arr3d[:,0,:] = 17

In [23]:
arr3d

array([[[17, 17, 17],
        [ 4,  5,  6]],

       [[17, 17, 17],
        [10, 11, 12]]])